# Generated by Django 2.2.5 on 2019-10-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191011_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feartured',
            field=models.BooleanField(default=False),
        ),
    ]
