# Generated by Django 2.2.5 on 2019-10-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_feartured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feartured',
            new_name='featured',
        ),
    ]
